name = "zilang-web"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-06-26"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "zilang"
database_id = "c1eb865b-c262-41fe-95e6-76566fddcbeb"
migrations_dir = "drizzle"

[observability]
enabled = true
