packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^24.0.4
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  typescript: ^5.8.3
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: "^4.1.10"
