/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'pump-controllers': PumpController;
    packaging: Packaging;
    testimonials: Testimonial;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'pump-controllers': PumpControllersSelect<false> | PumpControllersSelect<true>;
    packaging: PackagingSelect<false> | PackagingSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    site: Site;
    company: Company;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * 替代文本是媒体内容的描述，当媒体无法显示时，替代文本会显示在客户端
   */
  alt: string;
  caption?: string | null;
  /**
   * 用于在客户端显示模糊的预览图，无需手动设置
   */
  blurDataUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  content: (MediaBlockType | HeroBlockType | TestimonialsBlockType)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType".
 */
export interface MediaBlockType {
  /**
   * 选择一个媒体文件
   */
  media: string | Media;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType".
 */
export interface HeroBlockType {
  carousel?:
    | {
        media: string | Media;
        title: string;
        description: string;
        primaryCTA: string;
        primaryCTAUrl: string;
        secondaryCTA?: string | null;
        secondaryCTAUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 如果勾选，则滚动横幅会循环播放
   */
  loop?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType".
 */
export interface TestimonialsBlockType {
  title: string;
  description?: string | null;
  testimonials: (string | Testimonial)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  avatar?: (string | null) | Media;
  country: string;
  star: 'one' | 'two' | 'three' | 'four' | 'five';
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pump-controllers".
 */
export interface PumpController {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  series: 'gs+' | 'gs' | 'ps';
  category: 'standard' | 'smart' | 'auto';
  excerpt?: string | null;
  modelName: string;
  gallery?: (string | Media)[] | null;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  voltage: {
    min: number;
    max: number;
  };
  contactLoad: string;
  relayLife: number;
  maxCurrent: number;
  maxPower: number;
  maxPressure: number;
  extremePressure: number;
  startingPressure: {
    min: number;
    max: number;
  };
  frequency?: {
    min?: number | null;
    max?: number | null;
  };
  protectionGrade: string;
  threadInterface: string;
  switchChar?: string | null;
  temperature: number;
  flowSwitch?: ('reed' | 'none') | null;
  startingMethod?: ('auto' | 'manual' | 'pressure' | 'temperature') | null;
  buffer?: string | null;
  verticalHeight: number;
  packaging: string | Packaging;
  related?: (string | PumpController)[] | null;
  /**
   * 根据数量不同填写不同的交货时间
   */
  leadTime?:
    | {
        min?: number | null;
        max?: number | null;
        /**
         * 填写交货时间，如：10 days
         */
        duration: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packaging".
 */
export interface Packaging {
  id: string;
  title: string;
  description?: string | null;
  size: {
    length: number;
    width: number;
    height: number;
  };
  quantity: number;
  weight: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'pump-controllers';
        value: string | PumpController;
      } | null)
    | ({
        relationTo: 'packaging';
        value: string | Packaging;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  blurDataUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  content?:
    | T
    | {
        mediaBlock?: T | MediaBlockTypeSelect<T>;
        heroBlock?: T | HeroBlockTypeSelect<T>;
        testimonialsBlock?: T | TestimonialsBlockTypeSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType_select".
 */
export interface MediaBlockTypeSelect<T extends boolean = true> {
  media?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType_select".
 */
export interface HeroBlockTypeSelect<T extends boolean = true> {
  carousel?:
    | T
    | {
        media?: T;
        title?: T;
        description?: T;
        primaryCTA?: T;
        primaryCTAUrl?: T;
        secondaryCTA?: T;
        secondaryCTAUrl?: T;
        id?: T;
      };
  loop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType_select".
 */
export interface TestimonialsBlockTypeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  testimonials?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pump-controllers_select".
 */
export interface PumpControllersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  series?: T;
  category?: T;
  excerpt?: T;
  modelName?: T;
  gallery?: T;
  description?: T;
  voltage?:
    | T
    | {
        min?: T;
        max?: T;
      };
  contactLoad?: T;
  relayLife?: T;
  maxCurrent?: T;
  maxPower?: T;
  maxPressure?: T;
  extremePressure?: T;
  startingPressure?:
    | T
    | {
        min?: T;
        max?: T;
      };
  frequency?:
    | T
    | {
        min?: T;
        max?: T;
      };
  protectionGrade?: T;
  threadInterface?: T;
  switchChar?: T;
  temperature?: T;
  flowSwitch?: T;
  startingMethod?: T;
  buffer?: T;
  verticalHeight?: T;
  packaging?: T;
  related?: T;
  leadTime?:
    | T
    | {
        min?: T;
        max?: T;
        duration?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packaging_select".
 */
export interface PackagingSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  size?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  quantity?: T;
  weight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  country?: T;
  star?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  /**
   * 如果勾选，则会在顶部导航栏显示品牌名称
   */
  showName?: boolean | null;
  name?: string | null;
  links?:
    | {
        type: 'internal' | 'external' | 'page';
        page?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * 如果勾选，则会在页脚显示联系方式
   */
  showContact?: boolean | null;
  /**
   * 如果勾选，则会在页脚显示地址
   */
  showAddress?: boolean | null;
  links?:
    | {
        type: 'internal' | 'external' | 'page';
        page?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: string;
  name: string;
  logo: string | Media;
  slogan?: string | null;
  address: {
    street: string;
    zip: string;
    city: string;
    country: string;
  };
  contact: {
    email: string;
    telephone: string;
    whatsapp: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  showName?: T;
  name?: T;
  links?:
    | T
    | {
        type?: T;
        page?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  showContact?: T;
  showAddress?: T;
  links?:
    | T
    | {
        type?: T;
        page?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  slogan?: T;
  address?:
    | T
    | {
        street?: T;
        zip?: T;
        city?: T;
        country?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        telephone?: T;
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}